<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.example</groupId>
    <artifactId>SwiftSeed</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <maven.compiler.source>25</maven.compiler.source>
        <maven.compiler.target>25</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>


    <repositories>
        <repository>
            <id>xpple</id>
            <url>https://maven.xpple.dev/maven2</url>
        </repository>
    </repositories>

    <dependencies>
        <dependency>
            <groupId>dev.xpple</groupId>
            <artifactId>cubiomes</artifactId>
            <version>0.0.0-2026.4.10.1775848358+6092570ca20f18f64148dd393c944dcfbf7f6525</version>
        </dependency>
    </dependencies>
</project>